services:
  open-webui:
    image: ghcr.io/podmania/open-webui:latest
    userns_mode: "keep-id"
    container_name: open-webui
    ports:
      
    volumes:
      
      - /etc/localtime:/etc/localtime:ro
    restart: always
